# Generated by Haxe 4.0.0-rc.2+175840a
# Hail to Mighty CRAXE!!!

{.experimental: "codeReordering".}

import nimboot

type 
    User = ref object of RootObj
        email:string
        id:int
        name:string

    OtherUser = ref object of RootObj
        id:int
        name:string

    Admin = ref object of RootObj
        email:string
        id:int
        level:int
        name:string

    SomeProc = proc():string
    SomeInt = int
    SomeUser = ClassUser

type 
    ClassUser = ref object of RootObj
        id : int
        name : string
        email : string

    TypedefTest = ref object of RootObj

    TypedefTestStatic = object of RootObj


let TypedefTestStaticInst = TypedefTestStatic()

proc initClassUser(this:ClassUser, id:int, name:string, email:string) {.inline.} =
    this.id = id
    this.name = name
    this.email = email

proc newClassUser(id:int, name:string, email:string) : ClassUser {.inline.} =
    result = ClassUser()
    initClassUser(result, id, name, email)

proc `$`(this:ClassUser) : string {.inline.} = 
    result = "ClassUser" & $this[]

proc main(this:TypedefTestStatic) : void =
    var user = Admin(id:33, name:"Batman", email:"batman@batman.com", level:1)
    var arr = newHaxeArray[tuple[obj:RootRef, email:ptr string, id:ptr int, name:ptr string]]()
    discard arr.push((
        obj:user,
        email:addr user.email,
        id:addr user.id,
        name:addr user.name,
    ))
    var obj = arr[0]
    echo arr
    obj.email[] = "shit"
    echo obj.email[]
    echo user.email
    echo arr[0].email[]

proc `$`(this:TypedefTest) : string {.inline.} = 
    result = "TypedefTest" & $this[]

TypedefTestStaticInst.main()