# Generated by Haxe 4.0.0-rc.2+77068e10c
# coding: utf-8



class _hx_AnonObject:
    def __init__(self, fields):
        self.__dict__ = fields
    def __repr__(self):
        return repr(self.__dict__)


class ClassUser:
    __slots__ = ("id", "name", "email")

    def __init__(self,id,name,email):
        self.id = id
        self.name = name
        self.email = email



class TypedefTest:
    __slots__ = ()

    @staticmethod
    def main():
        user = _hx_AnonObject({'id': 33, 'name': "Batman", 'email': "batman@batman.com", 'level': 1})
        arr = list()
        arr.append(user)
        clsUser = ClassUser(44,"Superman","super@gmail.com")
        arr.append(clsUser)
        obj = (arr[0] if 0 < len(arr) else None)
        print(str(obj.email))
        obj.email = "shit"
        print(str(user.email))


class python_internal_ArrayImpl:
    __slots__ = ()

    @staticmethod
    def _get(x,idx):
        if ((idx > -1) and ((idx < len(x)))):
            return x[idx]
        else:
            return None


class python_internal_MethodClosure:
    __slots__ = ("obj", "func")

    def __init__(self,obj,func):
        self.obj = obj
        self.func = func

    def __call__(self,*args):
        return self.func(self.obj,*args)




TypedefTest.main()
