# Generated by Haxe 4.0.0-rc.2+77068e10c
# Hail to Mighty CRAXE!!!

{.experimental: "codeReordering".}

import nimboot

type 
    Box[T] = ref object of RootObj
        value : T

    Pair[K,V] = ref object of RootObj
        key : K
        value : V

    GenericsTest = ref object of RootObj

    GenericsTestStatic = object of RootObj


let GenericsTestStaticInst = GenericsTestStatic()

proc initBox[T](this:Box[T], value:T) {.inline.} =
    this.value = value

proc newBox[T](value:T) : Box[T] {.inline.} =
    result = Box[T]()
    initBox(result, value)

proc `$`(this:Box) : string {.inline.} = 
    result = "Box" & $this[]

proc initPair[K,V](this:Pair, key:K, value:V) {.inline.} =
    this.key = key
    this.value = value

proc newPair[K,V](key:K, value:V) : Pair[K,V] {.inline.} =
    result = Pair[K,V]()
    initPair(result, key, value)

proc `$`(this:Pair) : string {.inline.} = 
    result = "Pair" & $this[]

proc main(this:GenericsTestStatic) : void =
    var box = newBox(33)
    LogStaticInst.trace(box.value, "src/GenericsTest.hx", 22, "GenericsTest", "main")
    var pair = newPair(newBox("Hello"), 44)
    LogStaticInst.trace(pair.key, "src/GenericsTest.hx", 24, "GenericsTest", "main")
    LogStaticInst.trace(pair.value, "src/GenericsTest.hx", 25, "GenericsTest", "main")

proc `$`(this:GenericsTest) : string {.inline.} = 
    result = "GenericsTest" & $this[]

GenericsTestStaticInst.main()