# Generated by Haxe 4.0.0-rc.2+175840a
# Hail to Mighty CRAXE!!!

{.experimental: "codeReordering".}

import nimboot
import typetraits

type 
    IUser = tuple[
        obj : ref RootObj,
        name : ptr string,
        getKey : proc ():string
    ]

    User = ref object of RootObj

    ServiceUser = ref object of User
        name : string

    Interfaces = ref object of RootObj

    InterfacesStatic = ref object of RootObj

let InterfacesStaticInst = InterfacesStatic()

converter toIUser(this:ServiceUser) : IUser =
    return (
        obj: this,
        name: addr this.name,
        getKey: proc ():string = this.getKey()
    )

template checkType(this:IUser, some:untyped):bool =
    this.obj of some

template checkType(this:ref RootObj, some:untyped):bool =
    this of some

template castType[T](this:IUser, some:typedesc[T]):T =
    cast[T](this.obj)

template castType[T](this:ref RootObj, some:typedesc[T]):T =
    cast[T](this)

proc initServiceUser(this:ServiceUser) {.inline.} =
    discard

proc newServiceUser() : ServiceUser {.inline.} =
    result = ServiceUser()
    initServiceUser(result)

proc getKey(this:ServiceUser) : string =
    return "12345"

proc `$`(this:ServiceUser) : string {.inline.} = 
    result = "ServiceUser" & $this[]

proc testCheck(this:ref RootObj) =
    echo checkType(this, User)

proc processUser(this:InterfacesStatic, user:IUser) : void =
    var key = user.getKey()
    let suser = castType(user, ServiceUser)
    echo suser.name
    LogStaticInst.trace(key, "src/Interfaces.hx", 19, "Interfaces", "processUser")
    LogStaticInst.trace(user.name[], "src/Interfaces.hx", 20, "Interfaces", "processUser")

proc main(this:InterfacesStatic) : void =
    var user = newServiceUser()
    testCheck(user)
    user.name = "Batman"
    InterfacesStaticInst.processUser(user)

proc `$`(this:Interfaces) : string {.inline.} = 
    result = "Interfaces" & $this[]

InterfacesStaticInst.main()