// Generated by Haxe 4.0.0-rc.2+175840a
(function () { "use strict";
var SomeKey = function(key) {
	this.key = key;
};
SomeKey.prototype = {
	hashCode: function() {
		return this.key.length;
	}
};
var MapTest = function() { };
MapTest.main = function() {
	var objmap = new haxe_ds_StringMap();
	var _g = 0;
	while(_g < 10000000) {
		var i = _g++;
		var key = i == null ? "null" : "" + i;
		if(__map_reserved[key] != null) {
			objmap.setReserved(key,i);
		} else {
			objmap.h[key] = i;
		}
	}
	console.log("src/MapTest.hx:40:",__map_reserved["1000"] != null ? objmap.getReserved("1000") : objmap.h["1000"]);
};
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.prototype = {
	setReserved: function(key,value) {
		if(this.rh == null) {
			this.rh = { };
		}
		this.rh["$" + key] = value;
	}
	,getReserved: function(key) {
		if(this.rh == null) {
			return null;
		} else {
			return this.rh["$" + key];
		}
	}
};
var __map_reserved = {};
MapTest.main();
})();
