// Generated by Haxe 4.0.0-rc.3+e3df7a448
(function ($global) { "use strict";
class HxOverrides {
	static iter(a) {
		return { cur : 0, arr : a, hasNext : function() {
			return this.cur < this.arr.length;
		}, next : function() {
			return this.arr[this.cur++];
		}};
	}
}
class Role {
	constructor(name) {
		this.name = name;
	}
}
class User {
	constructor(roles,some) {
		this.roles = HxOverrides.iter(roles);
		this.some = some;
	}
}
class IteratorsTest {
	static main() {
		var user = new User([new Role("Admin"),new Role("User")],{ name : "GOOD", test : function() {
			return 3;
		}});
		var role = user.roles;
		while(role.hasNext()) {
			var role1 = role.next();
			console.log("src/IteratorsTest.hx:32:",role1.name);
		}
	}
}
IteratorsTest.main();
})({});
